//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Invoice_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_invoice_details()
        {
            this.tbl_invoice_payments = new HashSet<tbl_invoice_payments>();
            this.tbl_invoice_products = new HashSet<tbl_invoice_products>();
        }
    
        public int Invoice_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<double> Total_Amount { get; set; }
    
        public virtual tbl_customers tbl_customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice_payments> tbl_invoice_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_invoice_products> tbl_invoice_products { get; set; }
    }
}
