//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Invoice_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_invoice_products
    {
        public int Invoice_Product_Id { get; set; }
        public Nullable<int> Invoice_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual tbl_invoice_details tbl_invoice_details { get; set; }
        public virtual tbl_Products tbl_Products { get; set; }
    }
}
